/**
 * Markdown rendering parity: the ported renderer (src/lib/markdown/render.ts)
 * must produce byte-identical HTML to the original vanilla-app renderer.
 * Expected outputs live in scripts/fixtures/render-expected.json (generated by
 * scripts/gen-fixtures.ts while the legacy app still existed).
 * Run: npm run test:parity
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!doctype html><html><body></body></html>', {
  url: 'https://localhost/',
  pretendToBeVisual: true
});

const g = globalThis as unknown as Record<string, unknown>;
g.window = dom.window;
g.document = dom.window.document;
g.self = dom.window;

const marked = (await import('marked')).marked;
const hljs = (await import('highlight.js')).default;
const katex = (await import('katex')).default;
const DOMPurify = (await import('dompurify')).default;

const w = dom.window as unknown as Record<string, unknown>;
w.marked = marked;
w.hljs = hljs;
w.katex = katex;
w.DOMPurify = DOMPurify;

const mine = await import('../src/lib/markdown/render');

const expected = JSON.parse(
  readFileSync(join(process.cwd(), 'scripts', 'fixtures', 'render-expected.json'), 'utf8')
) as Record<string, string>;

const CASES: Array<[string, string]> = [
  ['empty', ''],
  ['emphasis', 'Hello **world** and *italics*'],
  ['heading + list', '# Title\n\n- one\n- two\n  - nested'],
  ['js code block', '```js\nconst x = 1;\nconsole.log(x);\n```'],
  ['no-lang code block', '```\nplain code\n```'],
  ['raw html sanitized', 'Text with <script>alert(1)</script> and <img src=x onerror=alert(1)>'],
  ['inline math', 'Inline $x^2 + y^2 = z^2$ math'],
  ['block math', 'Block:\n\n$$\n\\int_0^1 x^2 dx\n$$'],
  ['price stays text', 'That costs $100$ today'],
  ['canvas doc block', '<canvas title="My Doc" type="doc">\n# Heading\nbody\n</canvas>\ntail'],
  ['canvas code block', '<canvas lang="js" title="App">const a=1;</canvas>'],
  ['unfinished canvas tail', 'before <canvas title="X">'],
  ['gfm table', '| a | b |\n|---|---|\n| 1 | 2 |'],
  ['links and images', '[link](https://example.com) and ![img](https://x/y.png)'],
  ['html code block', '```html\n<div class="x">hi</div>\n```'],
  ['strikethrough + inline code', '~~strike~~ and `inline code`'],
  ['nested list + code', '- item\n\n  ```python\n  print("hi")\n  ```'],
  ['multi paragraph', 'Line one.\n\nLine two with a [ref](https://a.b/c).\n\nLast line.'],
  ['javascript: link sanitized', '[bad](javascript:alert(1))']
];

let failures = 0;
for (const [label, input] of CASES) {
  const want = expected[label];
  if (want === undefined) {
    failures++;
    console.log(`  FAIL ${label} (missing fixture)`);
    continue;
  }
  let actual: string;
  try {
    actual = mine.renderMarkdown(input);
  } catch (e) {
    actual = `THREW: ${(e as Error).message}`;
  }

  if (want === actual) {
    console.log(`  ok   ${label}`);
  } else {
    failures++;
    console.log(`  FAIL ${label}`);
    console.log(`       expected: ${want}`);
    console.log(`       ported:   ${actual}`);
  }
}

// Plain mode (Canvas editor) — no code-block action buttons.
const plain = '```js\nconst x = 1;\n```';
const wantPlain = expected['__plain__'] ?? '';
const minePlain = mine.renderMarkdownPlain(plain);
if (wantPlain === minePlain) {
  console.log('  ok   plain code mode');
} else {
  failures++;
  console.log('  FAIL plain code mode');
  console.log(`       expected: ${wantPlain}`);
  console.log(`       ported:   ${minePlain}`);
}

console.log(failures === 0 ? '\nALL PASSED' : `\n${failures} FAILED`);
process.exit(failures === 0 ? 0 : 1);
